project_name: maestro

builds:
- main: ./cmd/maestro/main.go
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  flags:
  - -mod=vendor
  - -v
  ldflags:
  - -X main.version=v{{ .Version }}
  - -X main.build={{ .ShortCommit }}
  - -X main.label=release
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  ignore:
  - goos: darwin
    goarch: 386

archives:
- name_template: "maestro-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip
  files: [a-workaround-to-include-only-the-binary*]
  wrap_in_directory: false

brews:
  - github:
      owner: jexia
      name: homebrew-cask
    skip_upload: true
    folder: Formula
    homepage:  https://github.com/jexia/maestro
    description: A straightforward service orchestrator
    test: |
      system "#{bin}/maestro -v"

checksum:
  name_template: "maestro-{{ .Version }}-checksums.sha256"

release:
  github:
    owner: jexia
    name: maestro

changelog:
  skip: true